version: "3"

services:
    vite:
        image: node:20.6-buster
        ports:
            - 9999:9999
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
        network_mode: host
        command: npm run dev
